runtime: python311
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  PROJECT_ID: "your-gcp-project-id"
  REGION: "us-central1"
  BATCH_SIZE: "50"
  PARALLELISM: "50"
  CONTAINER_IMAGE: "gcr.io/your-gcp-project-id/video-processor:latest"
  TOPIC_NAME: "video-processing-topic"